/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MercadinhoOriente.screen;

import MercadinhoOriente.function.DAO;
import MercadinhoOriente.main.Cashier;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class Screen extends javax.swing.JFrame {

    private final Scanner scan = new Scanner(System.in);

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
        jDesktopPaneTelas.setVisible(false);
        jInternalFrameFechamento.setVisible(false);
        jInternalFrameVisualizar.setVisible(false);
        jInternalFrameEditar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMain = new javax.swing.JDesktopPane();
        jButtonFecharCaixa = new javax.swing.JButton();
        jButtonVisualizar = new javax.swing.JButton();
        jButtonEditarFechamento = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jDesktopPaneTelas = new javax.swing.JDesktopPane();
        jInternalFrameFechamento = new javax.swing.JInternalFrame();
        jButtonFechaVoltar = new javax.swing.JButton();
        jTextFieldVendaCartão = new javax.swing.JTextField();
        jTextFieldDespesa = new javax.swing.JTextField();
        jTextFieldFerias = new javax.swing.JTextField();
        jLabelVendasCartao = new javax.swing.JLabel();
        jLabelDespesa = new javax.swing.JLabel();
        jLabelFerias = new javax.swing.JLabel();
        jButtonRegistrarFecho = new javax.swing.JButton();
        jLabelTurn = new javax.swing.JLabel();
        jComboBoxTurn = new javax.swing.JComboBox<>();
        jLabelMes = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabelDia = new javax.swing.JLabel();
        jInternalFrameVisualizar = new javax.swing.JInternalFrame();
        jButtonVisuVoltar = new javax.swing.JButton();
        jComboBoxVisuMes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonVisuBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVisu = new javax.swing.JTextArea();
        jInternalFrameEditar = new javax.swing.JInternalFrame();
        jButtonEditarVoltar = new javax.swing.JButton();
        jTextFieldEditFerias = new javax.swing.JTextField();
        jLabelEditFerias = new javax.swing.JLabel();
        jButtonRegistrarEdit = new javax.swing.JButton();
        jLabelEditTurn = new javax.swing.JLabel();
        jComboBoxEditTurn = new javax.swing.JComboBox<>();
        jLabelEditMes = new javax.swing.JLabel();
        jComboBoxEditMes = new javax.swing.JComboBox<>();
        jComboBoxEditDia = new javax.swing.JComboBox<>();
        jLabelEditDia = new javax.swing.JLabel();
        jComboBoxEditItem = new javax.swing.JComboBox<>();
        jLabelEditEdit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFecharCaixa.setText("Fechar Caixa");
        jButtonFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCaixaActionPerformed(evt);
            }
        });

        jButtonVisualizar.setText("Visualizar Fechamento");
        jButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarActionPerformed(evt);
            }
        });

        jButtonEditarFechamento.setText("Editar Fechamento");
        jButtonEditarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarFechamentoActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jDesktopPaneMain.setLayer(jButtonFecharCaixa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneMain.setLayer(jButtonVisualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneMain.setLayer(jButtonEditarFechamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPaneMain.setLayer(jButtonSair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneMainLayout = new javax.swing.GroupLayout(jDesktopPaneMain);
        jDesktopPaneMain.setLayout(jDesktopPaneMainLayout);
        jDesktopPaneMainLayout.setHorizontalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDesktopPaneMainLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jDesktopPaneMainLayout.setVerticalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtonFecharCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonEditarFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jInternalFrameFechamento.setVisible(true);
        jInternalFrameFechamento.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jInternalFrameFechamentoHierarchyChanged(evt);
            }
        });
        jInternalFrameFechamento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jInternalFrameFechamentoPropertyChange(evt);
            }
        });

        jButtonFechaVoltar.setText("Voltar");
        jButtonFechaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaVoltarActionPerformed(evt);
            }
        });

        jTextFieldDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDespesaActionPerformed(evt);
            }
        });

        jTextFieldFerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFeriasActionPerformed(evt);
            }
        });

        jLabelVendasCartao.setText("Vendas cartão -");

        jLabelDespesa.setText("Despesas - ");

        jLabelFerias.setText("Férias -");

        jButtonRegistrarFecho.setBackground(new java.awt.Color(176, 196, 222));
        jButtonRegistrarFecho.setText("Registrar Fechamento");
        jButtonRegistrarFecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarFechoActionPerformed(evt);
            }
        });

        jLabelTurn.setText("Turno -");

        jComboBoxTurn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha", "Tarde" }));

        jLabelMes.setText("Mês -");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaActionPerformed(evt);
            }
        });

        jLabelDia.setText("Dia -");

        javax.swing.GroupLayout jInternalFrameFechamentoLayout = new javax.swing.GroupLayout(jInternalFrameFechamento.getContentPane());
        jInternalFrameFechamento.getContentPane().setLayout(jInternalFrameFechamentoLayout);
        jInternalFrameFechamentoLayout.setHorizontalGroup(
            jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jInternalFrameFechamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameFechamentoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVendasCartao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTurn))
                    .addComponent(jLabelMes)
                    .addComponent(jLabelDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrarFecho)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVendaCartão, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jInternalFrameFechamentoLayout.setVerticalGroup(
            jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameFechamentoLayout.createSequentialGroup()
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameFechamentoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameFechamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMes)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTurn)
                    .addComponent(jComboBoxTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVendasCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVendaCartão, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameFechamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButtonRegistrarFecho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButtonFechaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jDesktopPaneTelas.add(jInternalFrameFechamento);
        jInternalFrameFechamento.setBounds(0, 0, 650, 592);

        jInternalFrameVisualizar.setVisible(true);
        jInternalFrameVisualizar.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jInternalFrameVisualizarHierarchyChanged(evt);
            }
        });
        jInternalFrameVisualizar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jInternalFrameVisualizarPropertyChange(evt);
            }
        });

        jButtonVisuVoltar.setText("Voltar");
        jButtonVisuVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisuVoltarActionPerformed(evt);
            }
        });

        jComboBoxVisuMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel1.setText("Mês -");

        jButtonVisuBuscar.setBackground(new java.awt.Color(176, 196, 222));
        jButtonVisuBuscar.setText("Buscar");
        jButtonVisuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisuBuscarActionPerformed(evt);
            }
        });

        jTextAreaVisu.setColumns(20);
        jTextAreaVisu.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVisu);

        javax.swing.GroupLayout jInternalFrameVisualizarLayout = new javax.swing.GroupLayout(jInternalFrameVisualizar.getContentPane());
        jInternalFrameVisualizar.getContentPane().setLayout(jInternalFrameVisualizarLayout);
        jInternalFrameVisualizarLayout.setHorizontalGroup(
            jInternalFrameVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameVisualizarLayout.createSequentialGroup()
                .addGroup(jInternalFrameVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameVisualizarLayout.createSequentialGroup()
                        .addContainerGap(517, Short.MAX_VALUE)
                        .addComponent(jButtonVisuVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameVisualizarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jInternalFrameVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrameVisualizarLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxVisuMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButtonVisuBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrameVisualizarLayout.setVerticalGroup(
            jInternalFrameVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameVisualizarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jInternalFrameVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVisuMes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVisuBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVisuVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jDesktopPaneTelas.add(jInternalFrameVisualizar);
        jInternalFrameVisualizar.setBounds(0, 0, 650, 580);

        jInternalFrameEditar.setVisible(true);
        jInternalFrameEditar.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jInternalFrameEditarHierarchyChanged(evt);
            }
        });
        jInternalFrameEditar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jInternalFrameEditarPropertyChange(evt);
            }
        });

        jButtonEditarVoltar.setText("Voltar");
        jButtonEditarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarVoltarActionPerformed(evt);
            }
        });

        jTextFieldEditFerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditFeriasActionPerformed(evt);
            }
        });

        jLabelEditFerias.setText("Edição - ");

        jButtonRegistrarEdit.setBackground(new java.awt.Color(176, 196, 222));
        jButtonRegistrarEdit.setText("Registrar Edição");
        jButtonRegistrarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEditActionPerformed(evt);
            }
        });

        jLabelEditTurn.setText("Turno -");

        jComboBoxEditTurn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha", "Tarde" }));

        jLabelEditMes.setText("Mês -");

        jComboBoxEditMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboBoxEditDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabelEditDia.setText("Dia -");

        jComboBoxEditItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ferias", "Cartao", "Despesa", " " }));

        jLabelEditEdit.setText("Item a alterar -");

        javax.swing.GroupLayout jInternalFrameEditarLayout = new javax.swing.GroupLayout(jInternalFrameEditar.getContentPane());
        jInternalFrameEditar.getContentPane().setLayout(jInternalFrameEditarLayout);
        jInternalFrameEditarLayout.setHorizontalGroup(
            jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEditarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jInternalFrameEditarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditTurn)
                    .addComponent(jLabelEditMes)
                    .addComponent(jLabelEditDia)
                    .addComponent(jLabelEditEdit))
                .addGap(66, 66, 66)
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEditMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEditFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEditTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEditDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jInternalFrameEditarLayout.setVerticalGroup(
            jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEditarLayout.createSequentialGroup()
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEditarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jComboBoxEditDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEditDia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEditMes)
                    .addComponent(jComboBoxEditMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEditTurn)
                    .addComponent(jComboBoxEditTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditEdit))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEditFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditFerias, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonRegistrarEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jButtonEditarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jDesktopPaneTelas.add(jInternalFrameEditar);
        jInternalFrameEditar.setBounds(0, 0, 650, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPaneTelas)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPaneMain)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPaneTelas))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonEditarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarFechamentoActionPerformed

        jDesktopPaneMain.setVisible(false);
        jDesktopPaneTelas.setVisible(true);
        jInternalFrameEditar.setVisible(true);
    }//GEN-LAST:event_jButtonEditarFechamentoActionPerformed

    private void jButtonFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaActionPerformed

        jDesktopPaneMain.setVisible(false);
        jDesktopPaneTelas.setVisible(true);
        jInternalFrameFechamento.setVisible(true);

    }//GEN-LAST:event_jButtonFecharCaixaActionPerformed

    private void jButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarActionPerformed

        jDesktopPaneMain.setVisible(false);
        jDesktopPaneTelas.setVisible(true);
        jInternalFrameVisualizar.setVisible(true);
    }//GEN-LAST:event_jButtonVisualizarActionPerformed

    private void jButtonFechaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaVoltarActionPerformed

        jDesktopPaneTelas.setVisible(false);
        jInternalFrameFechamento.setVisible(false);
        jDesktopPaneMain.setVisible(true);
    }//GEN-LAST:event_jButtonFechaVoltarActionPerformed

    private void jInternalFrameFechamentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jInternalFrameFechamentoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameFechamentoPropertyChange

    private void jInternalFrameFechamentoHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jInternalFrameFechamentoHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameFechamentoHierarchyChanged

    private void jButtonVisuVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisuVoltarActionPerformed

        jDesktopPaneTelas.setVisible(false);
        jInternalFrameVisualizar.setVisible(false);
        jDesktopPaneMain.setVisible(true);
        jTextAreaVisu.setText("");
    }//GEN-LAST:event_jButtonVisuVoltarActionPerformed

    private void jInternalFrameVisualizarHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jInternalFrameVisualizarHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameVisualizarHierarchyChanged

    private void jInternalFrameVisualizarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jInternalFrameVisualizarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameVisualizarPropertyChange

    private void jTextFieldDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDespesaActionPerformed

    private void jTextFieldFeriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFeriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFeriasActionPerformed

    private void jButtonEditarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarVoltarActionPerformed

        jDesktopPaneTelas.setVisible(false);
        jInternalFrameVisualizar.setVisible(false);
        jDesktopPaneMain.setVisible(true);
    }//GEN-LAST:event_jButtonEditarVoltarActionPerformed

    private void jTextFieldEditFeriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditFeriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditFeriasActionPerformed

    private void jInternalFrameEditarHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jInternalFrameEditarHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameEditarHierarchyChanged

    private void jInternalFrameEditarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jInternalFrameEditarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrameEditarPropertyChange

    private void jButtonRegistrarFechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarFechoActionPerformed

        String dia = (String) jComboBoxDia.getSelectedItem();
        int day = Integer.valueOf(dia);

        String mes = (String) jComboBoxMes.getSelectedItem();
        int month = Integer.valueOf(mes);

        String turno = (String) jComboBoxTurn.getSelectedItem();
        boolean turn;

        if (turno.equalsIgnoreCase("manha")) {
            turn = true;
        } else {
            turn = false;
        }

        String ferias = jTextFieldFerias.getText();
        double billing = Double.valueOf(ferias);

        String cartao = jTextFieldVendaCartão.getText();
        double saleCard = Double.parseDouble(cartao);

        String despesa = jTextFieldDespesa.getText();
        double expense = Double.parseDouble(despesa);

        DAO dao = new DAO();

        try {
            dao.closing(day, month, turn, billing, saleCard, expense);
            JOptionPane.showMessageDialog(rootPane, "Caixa fechado com sucesso!");
            jComboBoxDia.setSelectedIndex(0);
            jComboBoxMes.setSelectedIndex(0);
            jComboBoxTurn.setSelectedIndex(0);
            jTextFieldFerias.setText("");
            jTextFieldVendaCartão.setText("");

            jTextFieldDespesa.setText("");
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonRegistrarFechoActionPerformed

    private void jComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaActionPerformed


    }//GEN-LAST:event_jComboBoxDiaActionPerformed

    private void jButtonRegistrarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEditActionPerformed

        String dia = (String) jComboBoxEditDia.getSelectedItem();
        int day = Integer.valueOf(dia);

        String mes = (String) jComboBoxEditMes.getSelectedItem();
        int month = Integer.valueOf(mes);

        String turno = (String) jComboBoxEditTurn.getSelectedItem();
        boolean turn;

        if (turno.equalsIgnoreCase("manha")) {
            turn = true;
        } else {
            turn = false;
        }

        String itemName = (String) jComboBoxEditItem.getSelectedItem();
        int item = 0;

        if (itemName.equalsIgnoreCase("ferias")) {
            item = 1;
        } else if (itemName.equalsIgnoreCase("cartao")) {
            item = 2;
        } else if (itemName.equalsIgnoreCase("despesa")) {
            item = 3;
        }

        String edicao = jTextFieldEditFerias.getText();
        double edit = Double.parseDouble(edicao);

        DAO dao = new DAO();

        try {
            dao.edit(day, month, turn, item, edit);
            JOptionPane.showMessageDialog(rootPane, "Caixa editado com sucesso!");
            jComboBoxEditDia.setSelectedIndex(0);
            jComboBoxEditMes.setSelectedIndex(0);
            jComboBoxEditTurn.setSelectedIndex(0);
            jComboBoxEditItem.setSelectedItem(0);
            jTextFieldEditFerias.setText("");

        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRegistrarEditActionPerformed

    private void jButtonVisuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisuBuscarActionPerformed

        String mes = (String) jComboBoxVisuMes.getSelectedItem();
        int month = Integer.valueOf(mes);

        DAO dao = new DAO();
        Cashier cashier = new Cashier();

        try {
            for (Cashier c : dao.cashierList(month)) {
                jTextAreaVisu.setText(jTextAreaVisu.getText() + c.getTurn() + " - " + c.getDay() + " --- " + c.getBilling() + " --- " + c.getSaleCard() + " --- " + c.getExpense() + "\n");
            }
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVisuBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarFechamento;
    private javax.swing.JButton jButtonEditarVoltar;
    private javax.swing.JButton jButtonFechaVoltar;
    private javax.swing.JButton jButtonFecharCaixa;
    private javax.swing.JButton jButtonRegistrarEdit;
    private javax.swing.JButton jButtonRegistrarFecho;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVisuBuscar;
    private javax.swing.JButton jButtonVisuVoltar;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxEditDia;
    private javax.swing.JComboBox<String> jComboBoxEditItem;
    private javax.swing.JComboBox<String> jComboBoxEditMes;
    private javax.swing.JComboBox<String> jComboBoxEditTurn;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxTurn;
    private javax.swing.JComboBox<String> jComboBoxVisuMes;
    private javax.swing.JDesktopPane jDesktopPaneMain;
    private javax.swing.JDesktopPane jDesktopPaneTelas;
    private javax.swing.JInternalFrame jInternalFrameEditar;
    private javax.swing.JInternalFrame jInternalFrameFechamento;
    private javax.swing.JInternalFrame jInternalFrameVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDespesa;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelEditDia;
    private javax.swing.JLabel jLabelEditEdit;
    private javax.swing.JLabel jLabelEditFerias;
    private javax.swing.JLabel jLabelEditMes;
    private javax.swing.JLabel jLabelEditTurn;
    private javax.swing.JLabel jLabelFerias;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelTurn;
    private javax.swing.JLabel jLabelVendasCartao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVisu;
    private javax.swing.JTextField jTextFieldDespesa;
    private javax.swing.JTextField jTextFieldEditFerias;
    private javax.swing.JTextField jTextFieldFerias;
    private javax.swing.JTextField jTextFieldVendaCartão;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        String user = System.getProperty("user.name");
        String img = "C:\\Users\\"+user+"\\Documents\\MercadoOriente\\logo.png";
        setIconImage(Toolkit.getDefaultToolkit().getImage(img));
    }

}
